apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnfetr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnfetr
  template:
    metadata:
      labels:
        app: dnfetr
    spec:
      containers:
      - image: okteto.dev/dnfetr:latest
        name: dnfetr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "22dff185-a69a-428b-b450-e040cdaabfb1"
        - name: Vless_Path
          value: "/vl6sx"
        - name: Vmess_UUID
          value: "22dff185-a69a-428b-b450-e040cdaabfb1"
        - name: Vmess_Path
          value: "/vm6ss"
        - name: Share_Path
          value: "/v2link"
